//admin and user reducer types
export const SET_AUTHENTICATED_ADMIN = 'SET_AUTHENTICATED_ADMIN';
export const SET_AUTHENTICATED_USER = 'SET_AUTHENTICATED_USER';
export const SET_UNAUTHENTICATED_USER = 'SET_UNAUTHENTICATED_USER';
export const SET_UNAUTHENTICATED_ADMIN = 'SET_UNAUTHENTICATED_ADMIN';
export const SET_ADMIN = 'SET_ADMIN';
export const LOADING_ADMIN = 'LOADING_ADMIN';
export const SET_USER = 'SET_USER';
export const LOADING_USER = 'LOADING_USER';
export const SET_AUTHENTICATED_PATHNAMES = 'SET_AUTHENTICATED_PATHNAMES';

// export const MARCK_NOTIFICATIONS_READ = 'MARCK_NOTIFICATIONS_READ';


//ui reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const STOP_LOADING_UI = "STOP_LOADING_UI";


//Data reducer types
export const LOADING_DATA = "LOADING_DATA";
export const SET_MESSAGE = "SET_MESSAGE";
export const SET_ACTIVITIES_DATA = "SET_ACTIVITIES_DATA";
// export const ON_IMAGE_UPDATED = "ON_IMAGE_UPDATED";